meta_product_name: "Seed of Change"
meta_title: "Seed of Change - Défis pour l'écologie"
meta_description: "Défis tes amis et sois le plus éco-responsable du clan !"
meta_image: "landing-background.png" # should exist in `app/assets/images/`
